name: SurvivalGamesV3 BETA
main: SurvivalGamesV3\SurvivalGamesV3
version: 3.0.1
api: 3.0.0-ALPHA11



author: ImagicalGamer


commands:
    sg:
        usage: /sg make
        description: Make an SurvivalGames arena!
